### ISSUE TITLE
support for CAA record type

### ISSUE THREAD

**Issue by berlin-with0ut-return** [balliegojr/simple-dns#17]
hi, noticed CAA ([RFC 8659](https://www.rfc-editor.org/rfc/rfc8659.html)) is not one of the included `rdata` types in this library. are there plans for adding this? i have a use case which requires being able to parse and identify packets as CAA. 

if not, i'd be happy to work on this and raise a PR with CAA support. i imagine the process would be something similar to [this](https://github.com/balliegojr/simple-dns/commit/14ce45654989d958a41aba1da33d9da8cfca644e) commit where LOC was added?

**Comment by balliegojr** [comment]
Hi, sorry for taking this long to reply.

I haven't added any new RFCs to this library in a while, since I got caught on another project. 

I can add the support, but it will take a while to do it. but of course, any contribution is welcomed.

This RFC is part of the DNSSEC right? do you need just the record parsing or full DNSSEC validations? if just the parsing, then yes, it should be quite simple to add it to this library

**Comment by berlin-with0ut-return** [comment]
yes, for the current use case we only need very basic parsing. i will discuss with my team and start working on this :)

**Comment by berlin-with0ut-return** [comment]
#18 - i'm not super familiar with the standards you have for this repo or contributions so please feel free to let me know if any additional changes are needed!

**Comment by balliegojr** [comment]
Released 0.5.4 containing your change
