### ISSUE TITLE
Is this a wrong way to create CNAME records?

### ISSUE THREAD

**Issue by Nuhvi** [balliegojr/simple-dns#24]
I am trying to build and parse this CNAME record, and while it builds compressed and uncompressed just fine, it only parse uncompressed successfully.

Note if the `Name` of the ResourceRecord is `foo` or something else that can't be compressed, it is parsed fine.

```rust
      let mut packet = dns::Packet::new_reply(0);
      packet.answers.push(dns::ResourceRecord::new(
          dns::Name::new("_derp_region.iroh.").unwrap(),
          dns::CLASS::IN,
          30,
          dns::rdata::RData::CNAME(
              dns::Name::new("eu.derp.iroh.network")
                  .expect("is valid name")
                  .into(),
          ),
      ));

      let bytes = &packet.build_bytes_vec()?;
      let parsed = dns::Packet::parse(bytes)?;
      dbg!(parsed);
      // Successfully parsed

      let bytes = &packet.build_bytes_vec_compressed()?;
      let parsed = dns::Packet::parse(bytes)?;
      // Error: DnsError(InsufficientData)
```

**Comment by balliegojr** [comment]
I will take a look at this later today. It is likely a bug in the [de]compression code. 

Thanks for reporting

**Comment by balliegojr** [comment]
I've found the issue, the problem is in the compression code, in [this](https://github.com/balliegojr/simple-dns/blob/7c0bcdcf8bfb59526a18be02ed54ff76bff0a8c1/simple-dns/src/dns/name.rs#L107) function

The name compression works by creating pointers to previously seen domains, if you add the domain `foo.bar.baz`, it will be added fully in the packet, if later you add `buzz.foo.bar.baz` in the packet, the compression will write `buzz.[pointer to foo.bar.baz]`, a further addition of `xyz.buzz.foo.bar.baz` will result in `xyz.[pointer to buzz]`

The issue with the code, is that it is only looking at the current label, instead of looking at all the labels until the end of the domain.

When you add `eu.derp.iroh.network` the code wrongly creates a compression link to `iroh.`, but `eu.derp.iroh.network` can't be compressed in this situation because `iroh.` is different than `iroh.network`

I will work on a fix for this

**Comment by Nuhvi** [comment]
@balliegojr Thanks a lot. Could you also publish a new version, currently I am relying on installing from Github, and it is giving me grief while publishing to crates.io.

**Comment by balliegojr** [comment]
Sorry @Nuhvi, I forgot to publish a new version after merging your change.

I've just sent a fix for this issue to the main branch, can you confirm the issue was solved? Then I can publish a new version with both changes

**Comment by Nuhvi** [comment]
@balliegojr Sorry for the late reply, didn't have electricity :), Just confirmed, this works fine now. Looking forward for the new version.

**Comment by balliegojr** [comment]
Done. Published a new version with both changes

**Comment by Nuhvi** [comment]
Thanks, upgraded and published a new version too. I appreciate it.
